#!/bin/bash
if [[ $DOCKER_TAG == "*float*" ]];
then
    ALSVINN_USE_FLOAT=ON
else
    ALSVINN_USE_FLOAT=OFF
fi
echo $ALSVINN_USE_FLOAT
echo $DOCKERFILE_PATH
echo $IMAGE_NAME
cd ../../../
echo $(pwd)
docker build --build-arg ALSVINN_DOCKER_CONTAINER=$IMAGE_NAME --build-arg ALSVINN_USE_FLOAT=$ALSVINN_USE_FLOAT -f $DOCKERFILE_PATH -t $IMAGE_NAME .
