#!/bin/bash
# Tag specific git commit as well, but not release versions
if [[ $DOCKER_TAG == *"latest"* ]];
then
    # we want tag commit on the form "commit_id-float"
    TAG_WITH_COMMIT=${DOCKER_TAG//latest/${SOURCE_COMMIT}}
    docker tag $IMAGE_NAME $DOCKER_REPO:$TAG_WITH_COMMIT
    docker push $DOCKER_REPO:$TAG_WITH_COMMIT
fi
