hunter_config(Boost VERSION 1.68.0-p1 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON)

hunter_config(ZLIB VERSION 1.2.11-p0 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON)
hunter_config(hdf5 VERSION 1.8.15-p1 CMAKE_ARGS HDF5_ENABLE_PARALLEL=ON HDF5_BUILD_CPP_LIB=OFF CMAKE_POSITION_INDEPENDENT_CODE=ON)
