get_filename_component(PYTHON_BASE_INCLUDE_DIR ${PYTHON_INCLUDE_DIR} DIRECTORY)
get_filename_component(PYTHON_BASE_ROOT_DIR ${PYTHON_BASE_INCLUDE_DIR} DIRECTORY)

hunter_config(Boost VERSION 1.68.0-p1 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} PYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR} Python_ROOT_DIR=${PYTHON_BASE_ROOT_DIR} PYTHON_EXECUTABLE=${PYTHON_BASE_ROOT_DIR}/bin/python PYTHON_LIBRARY=${PYTHON_LIBRARY} PYTHON_VERSION=2.7.15 PYTHON_LIBRARIES=${PYTHON_LIBRARY})
