find_package(NetCDF REQUIRED)
add_library(netcdf::NetCDF4_c SHARED IMPORTED)
set_property(TARGET netcdf::NetCDF4_c PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${NETCDF_INCLUDE_DIR})
set_property(TARGET netcdf::NetCDF4_c PROPERTY IMPORTED_LOCATION ${NETCDF_LIBRARY})

add_library(netcdf::parallel_NetCDF4_c SHARED IMPORTED)
set_property(TARGET netcdf::parallel_NetCDF4_c PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${PNETCDF_INCLUDE_DIR})
set_property(TARGET netcdf::parallel_NetCDF4_c PROPERTY IMPORTED_LOCATION ${PNETCDF_LIBRARY})
